### ISSUE TITLE
Change requested for AppCenter: OARS data

### ISSUE THREAD

**Issue by cassidyjames** [writeas/writeas-gtk#11]
It appears your OARS data states `social-info` as `none`. However, since this app can upload user contents to the Internet (via the installed `writeas` component), it should be either `moderate` or `intense`.

**Comment by thebaer** [comment]
Wasn't sure about that category when following the [OARS data generator](https://hughsie.github.io/oars/generate.html). But I'm assuming `moderate` will be okay, since no personally-identifying information is shared with the server, and submitted data isn't used for ads or profiling.
