### ISSUE TITLE
Black bar appears on the left when scrollbar is visible

### ISSUE THREAD

**Issue by cassidyjames** [writeas/writeas-gtk#19]
After writing for a bit, sometimes I get this:

![screenshot from 2018-12-19 10 04 19](https://user-images.githubusercontent.com/611168/50235659-a113d800-0375-11e9-9c63-93126c172b8c.png)

I haven't yet figured out what's causing it.

**Comment by thebaer** [comment]
Thanks for the report. This is weird, it only seems to happen on elementary (not Ubuntu), and seems to have something to do with the padding on the `textview`. Will keep looking into this.
