### ISSUE TITLE
Build broken because code.as is down

### ISSUE THREAD

**Issue by SamWhited** [writeas/writeas-gtk#34]
Hello,

code.as is down and it is breaking the Arch package build because this repo is different and has submodules that use code.as so we can't update to using GitHub because the versions and tags don't match, but also couldn't build even if we did update to GitHub because submodules won't be able to initialize even if we maintained a separate Git package (the main package also can't be built because submodules don't exist in the tarball, for that issue see #33).

Please consider making this repo match what is on write.as and using consistent versioning going forward. Thank you for your time.

**Comment by SamWhited** [comment]
Ping

**Comment by NathanBnm** [comment]
@SamWhited seems to be resolved I think you can close this

**Comment by thebaer** [comment]
Sorry for the downtime, @SamWhited. We're paying more attention to it now.

**Comment by SamWhited** [comment]
Not to worry; thank you, and as always, let me know if there's anything I can do to help!
