### ISSUE TITLE
Version mismatch between GitHub and Gitea

### ISSUE THREAD

**Issue by SamWhited** [writeas/writeas-gtk#5]
Hi,

On GitHub the latest version is 1.0.2, but on the Gitea instance code.as, it's 1.0.1.
Which location is the canonical location for this package, or do you have a preference which one third party package managers use? If not, can you please push a release to code.as?

Thanks.

**Comment by thebaer** [comment]
The canonical location is on code.as -- I've just made a new release there, and I'll be sure to keep doing that for future releases. Thanks for bringing this up.

This repo is only for the elementaryOS build, so I'll adjust the name.

**Comment by thebaer** [comment]
Ah, thanks -- writeas-cli is up to date over there now.

For writeas-gtk I created a release, but it doesn't look like Gitea actually builds a release page like on GitHub. Still, the latest release (v1.0.1) is tagged, and has an archive available. Is there something else needed?

**Comment by SamWhited** [comment]
Isn't the latest release 1.0.2 on GitHub?

**Comment by thebaer** [comment]
Officially, it's the 1.0.1 release on Code.as

On GitHub, I needed to create the 1.0.1 and 1.0.2 tags to trigger a new build with elementaryOS's tools every time I wanted to try and get it working. I would've used a different tag format that made this more clear, but this was the only format their build tools accepted.

**Comment by SamWhited** [comment]
Oh geeze; that's confusing. So you'll be skipping 1.0.2 on code.as and the next release will be 1.0.3 presumably? It seems like managing the inconsistency would get confusing, but I'll update to whatever you release I guess. Thanks!
